<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo ASSET_SAYA ?>surat/style3.css" />
    <title>Laporan Pemakaian Barang CMP</title>
  </head>
   <body>
	
	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<div style="width:128mm;float:left;">
						<img src="<?php echo ASSET_SAYA ?>surat/logo.gif" />
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;">Generated By System : <span><</span> <?php echo date('d/m/Y H:i:s') ?> <span>></span></p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
						<h3 style="margin:0px;"><b>Laporan Pemakaian Barang CMP #<?php echo $listData[0]->kodeCmp ?></b></h3>
					<hr/>
					
					<div style="width:128mm;float:left;">
                                            <p style="text-align:left; margin-top:-2px">No CMP : <b><?php echo $listData[0]->kodeCmp ?></b> <br> Periode : <?php echo $listData[0]->kodePeriode ?>
						<br/>
						
						</p>
					</div>
					<div style="width:128mm;float:right;">
                                            <p style="text-align:right;margin-top:-2px;">Gudang : <?php echo $listData[0]->namagudang; ?><br>Tanggal Transaksi : <?php echo $listData[0]->tanggalAmbil ?></p>
					</div>
					<div style="clear:both;"></div>
					
					<center>
						<p style="font-weight:none;font-size:16pt">LAPORAN PEMAKAIAN BARANG CMP</p>
					</center>
                                        <table class="tb1" style="width: 100%;">
						<tr>
                                                        <td>No</td>
                                                        <td>Tanggal</td>
                                                        <td>Kegiatan</td>
                                                        <td>Gudang</td>
                                                        <td>Mesin</td>
                                                        <td>Nama Barang</td>
                                                        <td>Kode Barang</td>
                                                        <td>Sat</td>
                                                        <td>Qty</td>
                                                        <td>Harga Satuan</td>
                                                        <td>Total</td>
                                                        <td>Keterangan</td>
						</tr>
						
						<?php
                                        
                                                $no = 0 ;
                                                foreach($listData as $value){
                                                $no++;
                                                 ?>
						
						<tr class="isi-colom">
							<td style="font-size:7pt;"><?php echo $no; ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->tanggalAmbil ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->namaKegiatan ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->namagudang ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->namaMesin ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->namaBarang ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->kodeBarang ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->satuan ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->qtyCmpItem ?></td>
                                                        <td style="font-size:7pt;">Rp. <?php echo number_format($value->hargaSatuan, 0,'.','.') ?></td>
                                                        <td style="font-size:7pt;">Rp. <?php echo number_format($value->jumlahHarga, 0,'.','.') ?></td>
                                                        <td style="font-size:7pt;"> </td>
						</tr>
                                                
                                                <?php } ?>
					</table>
				</div>
			</div>    
		</div>
	</div>
   
   </body>
</html>
</html>