<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo ASSET_SAYA ?>surat/style3.css" />
    <title>Laporan Barang Dibawah Stok</title>
  </head>
   <body>
	
	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<div style="width:128mm;float:left;">
						<img src="<?php echo ASSET_SAYA ?>surat/logo.gif" />
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;">Generated By System : <span><</span> <?php echo date('d/m/Y H:i:s') ?> <span>></span></p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
						<h3 style="margin:0px;"><b>Laporan Barang Di Bawah Stok</b></h3>
					<hr/>
					
					<div style="width:128mm;float:left;">
						<p style="text-align:left; margin-top:-2px">Sampai dengan : <?php echo date('d/m/Y') ?>
						<br/>
						
						</p>
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;margin-top:-2px;"></p>
					</div>
					<div style="clear:both;"></div>
					
					<center>
						<p style="font-weight:none;font-size:16pt">LAPORAN BARANG DI BAWAH STOK</p>
					</center>
                                        <table class="tb1" style="width: 100%;">
						<tr>
                                                        <td width="50">No</td>
                                                        <td width="100">Kode Barang</td>
                                                        <td width="100">Nama Barang</td>
                                                        <td width="70">Satuan</td>
                                                        <td width="70">Batas Minimum</td>
                                                        <td width="70">Saldo Akhir</td>
						</tr>
						
						<?php
                                        
                                                $no = 0 ;
                                                foreach($listData as $value){
                                                $no++;
                                                 ?>
						
						<tr class="isi-colom">
							
							<td style="font-size:7pt;"><?php echo $no; ?></td>
                                                        <td style="font-size:7pt;"><a href="#"><?php echo $value->kodeBarang ?></a></td>
                                                        <td style="font-size:7pt;"><?php echo $value->namaBarang ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->satuan ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->qtyMinimum ?></td>
                                                        <td style="font-size:7pt;"><?php echo $value->currentStok ?></td>
						</tr>
                                                
                                                <?php } ?>
					</table>
				</div>
			</div>    
		</div>
	</div>
   
   </body>
</html>
</html>