<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo base_url('assets') ?>/surat/style3.css" />
    <title>Laporan Gajihan</title>
  </head>
   <body>
	
	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<div style="width:128mm;float:left;">
						<img src="<?php echo base_url('assets') ?>/surat/logo.gif" style="visibility:hidden;" />
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;"><button style="text-align:right;" onclick="window.history.back()">Back</button>&nbsp;&nbsp;&nbsp;<button style="text-align:right;" onclick="window.print()">Print</button></p>
						<p style="text-align:right;">Generated By System : <span><</span> <?php echo date('d/m/Y H:i:s') ?> <span>></span></p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
						<h3 style="margin:0px;"><b>Laporan Gajihan</b></h3>
					<hr/>
					
					<div style="width:128mm;float:left;">
						<p style="text-align:left; margin-top:-2px">Periode: <?php echo strtoupper($namaBulan.' '.$namaTahun); ?>
						<br/>
						
						</p>
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;margin-top:-2px;">Jabatan : <?php echo strtoupper($jabatan); ?></p>
					</div>
					<div style="clear:both;"></div>
					
					<center>
						<p style="font-weight:none;font-size:16pt">LAPORAN GAJIHAN</p>
					</center>
                                        <table class="tb1" style="width: 100%;">
						<tr>
                            <td>No</td>
                            <td>Nama</td>
                            <td>NIK</td>
                            <td>Jabatan</td>
                            <td>Golongan</td>
                            <td>Tanggal Transfer</td>
                            <td>Pajak</td>
                            <td>Gaji Netto</td>                  
						</tr>
						
						<?php
                                        
                        $no = 0 ;
                        $totalPajak = 0;
                        $totalNetto = 0;
                        foreach($listData as $value){
                        $no++;
                        $totalPajak = $totalPajak+$value['PotonganPajak'];
                        $totalNetto = $totalNetto+$value['GajiNetto'];
                        ?>
						
						<tr class="isi-colom">
							<td style="font-size:7pt;"><?php echo $no; ?></td>
                            <td style="font-size:7pt;"><?php echo $value['NamaKaryawan']; ?></td>
                            <td style="font-size:7pt;"><?php echo $value['NIK']; ?></td>
                            <td style="font-size:7pt;"><?php echo $value['NamaJabatan']; ?></td>
                            <td style="font-size:7pt;"><?php echo $value['NamaGolongan']; ?></td>
                            <td style="font-size:7pt;"><?php echo $this->m_umum->formatTanggal($value['TanggalTransfer'], 'd-m-Y'); ?></td>
                           
                            <td style="font-size:7pt;">Rp. <?php echo number_format($value['PotonganPajak'], 0,'.','.') ?></td>
                            <td style="font-size:7pt;">Rp. <?php echo number_format($value['GajiNetto'], 0,'.','.') ?></td>
                            
						</tr>
                                             
                        <?php } ?>
                        <tr>
                    		<td style="font-size:7pt;" colspan="6" align="right">Total</td>  
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($totalPajak, 0,'.','.') ?></td> 
                    		<td style="font-size:7pt;"  align="right">Rp. <?php echo number_format($totalNetto, 0,'.','.') ?></td>  
                        </tr>
					</table>
				</div>
			</div>    
		</div>
	</div>
   
   </body>
</html>
</html>